// src/vmgen.js
// Generates a unique, obfuscated Lua VM for every compilation.
// The VM itself uses randomized variable names and obfuscated control flow.

'use strict';

const { generateOpaquePredicates } = require('./junk');

/**
 * Generate a random variable name using invisible/lookalike unicode chars
 * to make the output look like gibberish
 */
function randomVar(prefix = '_') {
  const chars = 'lIiOo0';  // visually similar chars
  let name = prefix;
  const len = Math.floor(Math.random() * 6) + 4;
  for (let i = 0; i < len; i++) {
    name += chars[Math.floor(Math.random() * chars.length)];
  }
  // Add a random suffix to avoid collisions
  name += Math.floor(Math.random() * 9999).toString(36);
  return name;
}

/**
 * Generate the complete VM Lua source.
 * All internal variable names are randomized per compile.
 * The dispatch table is shuffled.
 */
function generateVM(opcodeTable, encryptedBytecode, encryptedConstants, decryptorLua, options = {}) {
  const { nameToNum } = opcodeTable;

  // Generate unique variable names for every internal symbol
  const V = {
    vm:         randomVar('_'),
    bc:         randomVar('_'),
    kst:        randomVar('_'),
    stack:      randomVar('_'),
    pc:         randomVar('_'),
    inst:       randomVar('_'),
    op:         randomVar('_'),
    a:          randomVar('_'),
    b:          randomVar('_'),
    c:          randomVar('_'),
    dispatch:   randomVar('_'),
    env:        randomVar('_'),
    i:          randomVar('_'),
    tmp:        randomVar('_'),
    tmp2:       randomVar('_'),
    running:    randomVar('_'),
    decode:     randomVar('_'),
    decodeK:    randomVar('_'),
    parseNum:   randomVar('_'),
    readBytes:  randomVar('_'),
    tonum:      randomVar('_'),
    encBC:      randomVar('_'),
    encKST:     randomVar('_'),
    prefix:     randomVar('_'),
  };

  // Unique prefix for decryptor vars (to avoid collision with VM vars)
  const decPrefix = randomVar('x');

  // Patch decryptor to use unique prefix
  let patchedDecryptor = decryptorLua
    .replace(/\bB_k1\b/g, `${decPrefix}k1`)
    .replace(/\bB_k2\b/g, `${decPrefix}k2`)
    .replace(/\bB_rm\b/g, `${decPrefix}rm`)
    .replace(/\bB_decode\b/g, `${decPrefix}decode`);

  // Make sure the decryptor function name is exactly the same as the call later
  patchedDecryptor = patchedDecryptor
    .replace(new RegExp(`\\b${decPrefix}decode\\b`, 'g'), `${decPrefix}decode`);

  // Opaque predicates for dead branches
  const preds = generateOpaquePredicates();

  // Build the opcode dispatch table as a Lua table
  // Keys are the randomized opcode numbers, values are handler function references
  const ops = nameToNum;

  // Generate a random number for dead loop (NOT JavaScript code)
  const randomLoopCount = Math.floor(Math.random() * 50) + 10;

  // Generate the full VM
  const vm = `
-- [[ Generated by LuaObf - Do not redistribute ]]
local ${V.encBC}="${encryptedBytecode}"
local ${V.encKST}="${encryptedConstants}"
${patchedDecryptor}
-- Opaque dead code (never executes)
if ${preds[0]} and false then error("${randomVar('e')}") end
local function ${V.parseNum}(${V.b},${V.i})
  local ${V.a}=${V.b}[${V.i}]
  local ${V.tmp}=${V.b}[${V.i}+1]
  local ${V.tmp2}=${V.b}[${V.i}+2]
  local ${V.op}=${V.b}[${V.i}+3]
  return (${V.a}<<24)|(${V.tmp}<<16)|(${V.tmp2}<<8)|${V.op},${V.i}+4
end
local function ${V.decodeK}(${V.b})
  local ${V.kst}={}
  local ${V.i}=1
  local ${V.a},_=${V.parseNum}(${V.b},${V.i})
  ${V.i}=${V.i}+4
  local ${V.tmp}=${V.a}
  for ${V.op}=1,${V.tmp} do
    local len,_=${V.parseNum}(${V.b},${V.i})
    ${V.i}=${V.i}+4
    local tag=${V.b}[${V.i}]
    ${V.i}=${V.i}+1
    if tag==0 then
      ${V.kst}[${V.op}]=nil
    elseif tag==1 then
      ${V.kst}[${V.op}]=${V.b}[${V.i}]==1
      ${V.i}=${V.i}+1
    elseif tag==2 or tag==3 then
      local slen,_=${V.parseNum}(${V.b},${V.i})
      ${V.i}=${V.i}+4
      local s=""
      for ${V.tmp2}=1,slen do
        s=s..string.char(${V.b}[${V.i}])
        ${V.i}=${V.i}+1
      end
      ${V.kst}[${V.op}]=tag==2 and tonumber(s) or s
    end
  end
  return ${V.kst}
end
local function ${V.readBytes}(${V.b})
  local instList={}
  local ${V.i}=1
  local count,_=${V.parseNum}(${V.b},${V.i})
  ${V.i}=${V.i}+4
  for ${V.op}=1,count do
    local opcode=${V.b}[${V.i}]
    local regA=${V.b}[${V.i}+1]
    local regB=(${V.b}[${V.i}+2]<<8)|${V.b}[${V.i}+3]
    local regC=(${V.b}[${V.i}+4]<<8)|${V.b}[${V.i}+5]
    instList[${V.op}]={op=opcode,a=regA,b=regB,c=regC}
    ${V.i}=${V.i}+6
  end
  return instList
end
-- Dead opaque branch
if ${preds[1]} and false then
  local ${randomVar('z')}={}
  for ${randomVar('z')}=1,100 do end
end
local ${V.bc}=${V.readBytes}(${decPrefix}decode(${V.encBC}))
local ${V.kst}=${V.decodeK}(${decPrefix}decode(${V.encKST}))
local ${V.stack}={}
local ${V.env}=getfenv and getfenv(0) or _G
local ${V.pc}=1
local ${V.running}=true
-- Dispatch handlers: op -> function(a,b,c)
local ${V.dispatch}={
  [${ops['LOADK']}]=function(${V.a},${V.b})${V.stack}[${V.a}]=${V.kst}[${V.b}+1]end,
  [${ops['LOADNIL']}]=function(${V.a})${V.stack}[${V.a}]=nil end,
  [${ops['LOADBOOL']}]=function(${V.a},${V.b},${V.c})${V.stack}[${V.a}]=${V.b}~=0;if ${V.c}~=0 then ${V.pc}=${V.pc}+1 end end,
  [${ops['MOVE']}]=function(${V.a},${V.b})${V.stack}[${V.a}]=${V.stack}[${V.b}]end,
  [${ops['GETGLOBAL']}]=function(${V.a},${V.b})
    local k=${V.kst}[${V.b}+1]
    ${V.stack}[${V.a}]=${V.env}[k]
  end,
  [${ops['SETGLOBAL']}]=function(${V.a},${V.b})
    local k=${V.kst}[${V.b}+1]
    ${V.env}[k]=${V.stack}[${V.a}]
  end,
  [${ops['GETTABLE']}]=function(${V.a},${V.b},${V.c})
    local tbl=${V.stack}[${V.b}]
    local key=type(${V.c})=="number" and (${V.c}>127 and ${V.kst}[${V.c}-127] or ${V.stack}[${V.c}]) or ${V.kst}[${V.c}+1]
    if tbl then ${V.stack}[${V.a}]=tbl[key] end
  end,
  [${ops['SETTABLE']}]=function(${V.a},${V.b},${V.c})
    local tbl=${V.stack}[${V.a}]
    local key=type(${V.b})=="number" and (${V.b}>127 and ${V.kst}[${V.b}-127] or ${V.stack}[${V.b}]) or ${V.kst}[${V.b}+1]
    local val=type(${V.c})=="number" and ${V.stack}[${V.c}] or ${V.c}
    if tbl then tbl[key]=val end
  end,
  [${ops['NEWTABLE']}]=function(${V.a})${V.stack}[${V.a}]={}end,
  [${ops['SELF']}]=function(${V.a},${V.b},${V.c})
    local tbl=${V.stack}[${V.b}]
    local key=${V.kst}[${V.c}+1]
    ${V.stack}[${V.a}+1]=tbl
    ${V.stack}[${V.a}]=tbl[key]
  end,
  [${ops['ADD']}]=function(${V.a},${V.b},${V.c})
    ${V.stack}[${V.a}]=(${V.stack}[${V.b}] or 0)+(${V.stack}[${V.c}] or 0)
  end,
  [${ops['SUB']}]=function(${V.a},${V.b},${V.c})
    ${V.stack}[${V.a}]=(${V.stack}[${V.b}] or 0)-(${V.stack}[${V.c}] or 0)
  end,
  [${ops['MUL']}]=function(${V.a},${V.b},${V.c})
    ${V.stack}[${V.a}]=(${V.stack}[${V.b}] or 0)*(${V.stack}[${V.c}] or 0)
  end,
  [${ops['DIV']}]=function(${V.a},${V.b},${V.c})
    local d=${V.stack}[${V.c}] or 1
    ${V.stack}[${V.a}]=(${V.stack}[${V.b}] or 0)/(d==0 and 1 or d)
  end,
  [${ops['MOD']}]=function(${V.a},${V.b},${V.c})
    local d=${V.stack}[${V.c}] or 1
    ${V.stack}[${V.a}]=(${V.stack}[${V.b}] or 0)%(d==0 and 1 or d)
  end,
  [${ops['POW']}]=function(${V.a},${V.b},${V.c})
    ${V.stack}[${V.a}]=(${V.stack}[${V.b}] or 0)^(${V.stack}[${V.c}] or 0)
  end,
  [${ops['UNM']}]=function(${V.a},${V.b})
    ${V.stack}[${V.a}]=-(${V.stack}[${V.b}] or 0)
  end,
  [${ops['NOT']}]=function(${V.a},${V.b})
    ${V.stack}[${V.a}]=not ${V.stack}[${V.b}]
  end,
  [${ops['LEN']}]=function(${V.a},${V.b})
    ${V.stack}[${V.a}]=#(${V.stack}[${V.b}] or "")
  end,
  [${ops['CONCAT']}]=function(${V.a},${V.b},${V.c})
    local parts={}
    for ${V.i}=${V.b},${V.c} do parts[#parts+1]=tostring(${V.stack}[${V.i}] or "")end
    ${V.stack}[${V.a}]=table.concat(parts)
  end,
  [${ops['JMP']}]=function(_,${V.b})${V.pc}=${V.b} end,
  [${ops['EQ']}]=function(${V.a},${V.b},${V.c})
    if (${V.stack}[${V.b}]==${V.stack}[${V.c}])~=(${V.a}~=0) then ${V.pc}=${V.pc}+1 end
  end,
  [${ops['LT']}]=function(${V.a},${V.b},${V.c})
    if (${V.stack}[${V.b}]<${V.stack}[${V.c}])~=(${V.a}~=0) then ${V.pc}=${V.pc}+1 end
  end,
  [${ops['LE']}]=function(${V.a},${V.b},${V.c})
    if (${V.stack}[${V.b}]<=${V.stack}[${V.c}])~=(${V.a}~=0) then ${V.pc}=${V.pc}+1 end
  end,
  [${ops['TEST']}]=function(${V.a},${V.b})
    if not(not not ${V.stack}[${V.a}])==(${V.b}~=0) then ${V.pc}=${V.pc}+1 end
  end,
  [${ops['CALL']}]=function(${V.a},${V.b})
    local fn=${V.stack}[${V.a}]
    if type(fn)~="function" then return end
    local args={}
    for ${V.i}=1,${V.b}-1 do args[${V.i}]=${V.stack}[${V.a}+${V.i}]end
    -- Fixed: table.unpack -> unpack for Lua 5.1 (Roblox)
    local res={pcall(fn,unpack(args))}
    if res[1] then ${V.stack}[${V.a}]=res[2] end
  end,
  [${ops['RETURN']}]=function(${V.a},${V.b})${V.running}=false end,
  [${ops['FORPREP']}]=function(${V.a})
    ${V.stack}[${V.a}]=(${V.stack}[${V.a}] or 0)-(${V.stack}[${V.a}+2] or 1)
  end,
  [${ops['FORLOOP']}]=function(${V.a},${V.b})
    ${V.stack}[${V.a}]=(${V.stack}[${V.a}] or 0)+(${V.stack}[${V.a}+2] or 1)
    if ${V.stack}[${V.a}]<=(${V.stack}[${V.a}+1] or 0) then
      ${V.stack}[${V.a}+3]=${V.stack}[${V.a}]
      ${V.pc}=${V.b}
    end
  end,
  [${ops['TFORLOOP']}]=function(${V.a},${V.b})
    local fn=${V.stack}[${V.a}]
    if type(fn)=="function" then
      local res={pcall(fn,${V.stack}[${V.a}+1],${V.stack}[${V.a}+2])}
      if res[1] and res[2]~=nil then
        ${V.stack}[${V.a}+2]=res[2]
        for ${V.i}=1,${V.b} do ${V.stack}[${V.a}+2+${V.i}]=res[${V.i}+1]end
      else
        ${V.pc}=${V.pc}+1
      end
    end
  end,
  [${ops['CLOSURE']}]=function(${V.a})${V.stack}[${V.a}]=function()end end,
  [${ops['VARARG']}]=function(${V.a})${V.stack}[${V.a}]=nil end,
}
-- Dead code block
do
  local ${randomVar('d')}=false
  if ${randomVar('d')} then
    for ${randomVar('d')}=1,${randomLoopCount} do end
  end
end
while ${V.running} and ${V.pc}<=#${V.bc} do
  ${V.inst}=${V.bc}[${V.pc}]
  ${V.pc}=${V.pc}+1
  if ${V.inst} then
    ${V.op}=${V.inst}.op
    ${V.a}=${V.inst}.a or 0
    ${V.b}=${V.inst}.b or 0
    ${V.c}=${V.inst}.c or 0
    local ${V.tmp}=${V.dispatch}[${V.op}]
    if ${V.tmp} then ${V.tmp}(${V.a},${V.b},${V.c})end
  end
end
`;

  return vm;
}

module.exports = { generateVM, randomVar };
